### ISSUE TITLE
Failed to import the required Python library (msrestazure) [BUG]

### ISSUE THREAD

**Issue by urskog84** [Azure/CloudShell#62]
Can not get the Ansible Azure Modules to work.
I follow the -> https://docs.microsoft.com/en-us/azure/developer/ansible/getting-started-cloud-shell?tabs=ansible#test-ansible-installation

## To Reproduce

```
$ cat create_rg.yml
---
- hosts: localhost
  connection: local
  tasks:
    - name: Creating resource group - "{{ name }}"
      azure_rm_resourcegroup:
        name: "{{ name }}"
        location: "{{ location }}"
      register: rg
    - debug:
        var: rg

$ ansible-playbook create_rg.yml --extra-vars "name=my_rg location=westeurope"
```

## Observed Behavior

```
PLAY [localhost] *************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Creating resource group - "my_rg"] *************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'msrest'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (msrestazure) on cc-ad1e3a99-69479cbb47-plm6f's Python /opt/ansible/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

PLAY RECAP *******************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

```
ansible 2.10.2
  config file = None
  configured module search path = ['/home/petter/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python3.7/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

**Comment by edyoung** [comment]
Thanks for the report! This was identified previously and a fix has been merged (#61). The changes should be deployed next week.

Sorry for the inconvenience. I will leave this open until the fix is deployed so others can see it.

A workaround in the interim is to install ansible and the relevant modules to your home directory:

```
pip install ansible
wget -nv -q https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
pip install -r requirements-azure.txt
```

This may take a few minutes to complete. After this point a copy of ansible is available in ~/.local/bin and can be run with:

./.local/bin/ansible-playbook

**Comment by urskog84** [comment]
Thanks @edyoung!

If I run `~/.local/bin/ansible-playbook` i can stand in the ansible folder tree

```
# runing playbook with 

$~/.local/bin/ansible-playbook -i inventory playbook.yml
```
You can close the issue after the deployment  (#61) is done.

**Comment by mathersb2j** [comment]
I ran into this issue as well and just wanted to thank you both for the posts!

**Comment by edyoung** [comment]
This should be resolved at this point. Sorry for the inconvenience.

**Comment by yashvanthkumar94** [comment]
Hi,

I am hitting the below similar error, wondering if there could be a possible workaround for this error at this point ?

Error message:

"msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on AZANWSPR01's Python /usr/libexec/platform-python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter".

Thank you

**Comment by kbrajeshwaran** [comment]
still getting the same error while running simple play book

- name: Create a resource group
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: devopscloud2731
        location: westus
        tags:
          Environment: dev

exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.core'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (msrestazure) on cc-69cea001-596ddf994c-spg2x's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, 
please consult the documentation on ansible_python_interpreter"}

**Comment by kbrajeshwaran** [comment]
there wont by any solution on google .Kindy check and share us any workaround for this issue.

**Comment by CKNAVIN1009** [comment]
Again we are facing same issue even with all the differnt kind of commands like creation resourcegroup, deletion RG, creation of vM and others.

Attaching the screenshot for the reference.

Can someone please help here.

![image](https://github.com/Azure/CloudShell/assets/104540425/08f89efd-78fc-4f9d-be77-b35a121a496b)

![image](https://github.com/Azure/CloudShell/assets/104540425/8afdf829-eb28-4226-97a3-c8b8acab2134)

**Comment by ebuildy** [comment]
Got same, using a virtual env with:

```
adal==1.2.7
aiohttp==3.9.1
aiosignal==1.3.1
ansible==9.1.0
ansible-core==2.16.2
antlr4-python3-runtime==4.13.1
anyio==4.2.0
applicationinsights==0.11.10
argcomplete==3.1.6
attrs==23.2.0
azure-appconfiguration==1.1.1
azure-batch==14.0.0
azure-cli==2.56.0
azure-cli-core==2.56.0
azure-cli-telemetry==1.1.0
azure-common==1.1.11
azure-containerregistry==1.1.0
azure-core==1.28.0
azure-cosmos==3.2.0
azure-data-tables==12.4.0
azure-datalake-store==0.0.53
azure-graphrbac==0.60.0
azure-identity==1.14.0
azure-iot-hub==2.6.1
azure-keyvault==4.2.0
azure-keyvault-administration==4.4.0b2
azure-keyvault-certificates==4.7.0
azure-keyvault-keys==4.9.0b3
azure-keyvault-secrets==4.7.0
azure-loganalytics==0.1.1
azure-mgmt-advisor==9.0.0
azure-mgmt-apimanagement==4.0.0
azure-mgmt-appconfiguration==3.0.0
azure-mgmt-appcontainers==2.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==4.0.0
azure-mgmt-automation==1.0.0
azure-mgmt-batch==17.0.0
azure-mgmt-batchai==7.0.0b1
azure-mgmt-billing==6.0.0
azure-mgmt-botservice==2.0.0
azure-mgmt-cdn==12.0.0
azure-mgmt-cognitiveservices==13.5.0
azure-mgmt-compute==30.4.0
azure-mgmt-containerinstance==10.1.0
azure-mgmt-containerregistry==10.1.0
azure-mgmt-containerservice==28.0.0
azure-mgmt-core==1.4.0
azure-mgmt-cosmosdb==9.4.0
azure-mgmt-databoxedge==1.0.0
azure-mgmt-datafactory==2.0.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==10.0.0
azure-mgmt-devtestlabs==4.0.0
azure-mgmt-dns==8.0.0
azure-mgmt-eventgrid==10.2.0b2
azure-mgmt-eventhub==10.1.0
azure-mgmt-extendedlocation==1.0.0b2
azure-mgmt-hdinsight==9.0.0
azure-mgmt-imagebuilder==1.2.0
azure-mgmt-iotcentral==10.0.0b2
azure-mgmt-iothub==3.0.0
azure-mgmt-iothubprovisioningservices==1.1.0
azure-mgmt-keyvault==10.3.0
azure-mgmt-kusto==0.3.0
azure-mgmt-loganalytics==13.0.0b4
azure-mgmt-managedservices==1.0.0
azure-mgmt-managementgroups==1.0.0
azure-mgmt-maps==2.0.0
azure-mgmt-marketplaceordering==1.1.0
azure-mgmt-media==9.0.0
azure-mgmt-monitor==5.0.1
azure-mgmt-msi==7.0.0
azure-mgmt-netapp==10.1.0
azure-mgmt-network==19.1.0
azure-mgmt-notificationhubs==7.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==1.1.0b4
azure-mgmt-privatedns==1.0.0
azure-mgmt-rdbms==10.2.0b13
azure-mgmt-recoveryservices==2.5.0
azure-mgmt-recoveryservicesbackup==7.0.0
azure-mgmt-redhatopenshift==1.4.0
azure-mgmt-redis==14.2.0
azure-mgmt-resource==23.1.0b2
azure-mgmt-search==9.1.0
azure-mgmt-security==5.0.0
azure-mgmt-servicebus==8.2.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-servicefabricmanagedclusters==1.0.0
azure-mgmt-servicelinker==1.2.0b1
azure-mgmt-signalr==2.0.0b1
azure-mgmt-sql==4.0.0b13
azure-mgmt-sqlvirtualmachine==1.0.0b5
azure-mgmt-storage==21.1.0
azure-mgmt-synapse==2.1.0b5
azure-mgmt-trafficmanager==1.0.0
azure-mgmt-web==7.2.0
azure-multiapi-storage==1.2.0
azure-nspkg==3.0.2
azure-storage-blob==12.11.0
azure-storage-common==1.4.2
azure-synapse-accesscontrol==0.5.0
azure-synapse-artifacts==0.18.0
azure-synapse-managedprivateendpoints==0.4.0
azure-synapse-spark==0.2.0
bcrypt==4.1.2
certifi==2023.11.17
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
colorama==0.4.6
cryptography==41.0.7
Deprecated==1.2.14
fabric==2.7.1
frozenlist==1.4.1
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==1.0.2
httpx==0.26.0
humanfriendly==10.0
hyperframe==6.0.1
idna==3.6
importlib-metadata==6.11.0
invoke==1.7.3
isodate==0.6.1
javaproperties==0.5.2
Jinja2==3.1.3
jmespath==1.0.1
jsondiff==2.0.0
knack==0.11.0
MarkupSafe==2.1.3
microsoft-kiota-abstractions==1.0.0
microsoft-kiota-authentication-azure==1.0.0
microsoft-kiota-http==1.2.0
microsoft-kiota-serialization-json==1.0.1
microsoft-kiota-serialization-text==1.0.0
msal==1.24.0b2
msal-extensions==1.0.0
msgraph-core==1.0.0a4
msgraph-sdk==1.0.0
msrest==0.7.1
msrestazure==0.6.4
multidict==6.0.4
oauthlib==3.2.2
opentelemetry-api==1.22.0
opentelemetry-sdk==1.22.0
opentelemetry-semantic-conventions==0.43b0
packaging==21.3
paramiko==2.12.0
pathlib2==2.3.7.post1
pendulum==3.0.0
pkginfo==1.9.6
portalocker==1.7.1
psutil==5.9.7
pycomposefile==0.0.30
pycparser==2.21
PyGithub==1.59.1
Pygments==2.17.2
PyJWT==2.8.0
PyNaCl==1.5.0
pyOpenSSL==23.3.0
pyparsing==3.1.1
PySocks==1.7.1
python-dateutil==2.8.2
PyYAML==6.0.1
requests==2.31.0
requests-oauthlib==1.3.1
resolvelib==1.0.1
scp==0.13.6
semver==2.13.0
six==1.16.0
sniffio==1.3.0
sshtunnel==0.1.5
std-uritemplate==0.0.50
tabulate==0.9.0
time-machine==2.13.0
typing_extensions==4.9.0
tzdata==2023.4
uamqp==1.6.6
urllib3==2.1.0
websocket-client==1.3.3
wrapt==1.16.0
xmltodict==0.13.0
yarl==1.9.4
zipp==3.17.
```
